apiVersion: apps/v1
kind: Deployment

metadata:
  name: eris-deployment
  namespace: eris

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: eris

  template:
    metadata:
      labels:
        app: eris

    spec:
      containers:
        - name: eris-container
          image: harrydocker8971/eris:v1

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1Gi"

          envFrom:
            - secretRef:
                name: eris-secret
            - configMapRef:
                name: eris-config

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
